In [28]:
import numpy as np

# Input neurons [Hrs slept, Hrs studied]
x = np.array(([2,9],[1,5],[3,6])) 
# Output neurons [marks]
y = np.array(([92],[86],[89]))
# Normalizing to make values between 0 and 1
x=x/10
y=y/100


In [29]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
    
def sigmoid_grad(x):
    return x*(1-x)

# Set training iterations
epoch = 1000
# Setting learning rate (eta)
eta = 0.1
# Number of features in data set
input_neurons = 2
hidden_neurons = 3
output_neurons = 1

# Weight and bias - Random initialization
wh=np.random.uniform(size=(input_neurons,hidden_neurons)) # 2x3
print(wh)
bh=np.random.uniform(size=(1,hidden_neurons)) # 1x3
print(bh)
wout=np.random.uniform(size=(hidden_neurons,output_neurons)) # 3x1
print(wout)
bout=np.random.uniform(size=(1,output_neurons))
print(bout)



[[0.5937226  0.70039459 0.82432363]
 [0.33080752 0.73964389 0.78941459]]
[[0.74516066 0.75432119 0.32960125]]
[[0.14348957]
 [0.2613418 ]
 [0.73057453]]
[[0.32261838]]


In [30]:
for i in range(epoch):
    # Forward Propogation
    h_ip=np.dot(x,wh)+bh # Dot product + bias
    print(h_ip)
    h_act= sigmoid(h_ip) # Activation function
    o_ip=np.dot(h_act,wout)+bout
    output= sigmoid(o_ip)
    
    # Backpropagation
    # Error at Output layer
    Eo=y-output # Error at o/p
    outgrad= sigmoid_grad(output)
    d_output = Eo* outgrad # Errj=Oj(1-Oj)(Tj-Oj)
    print("the d_output is \n",d_output)
    
    # Error at Hidden later
    Eh=d_output.dot(wout.T) # .T means transpose
    hiddengrad= sigmoid_grad(h_act) # How much hidden layer wts contributed to error
    d_hidden= Eh *hiddengrad
    wout += h_act.T.dot(d_output)*eta # Dotproduct of nextlayererror and currentlayerop
    wh += x.T.dot(d_hidden)*eta
    
print("Normalized input: \n"+str(x))
print("Actual output: \n"+ str(y))
print("Predicted output: \n",output)

959e-03]
 [-2.20999980e-03]
 [-8.35044349e-05]]
[[1.18718203 1.58779943 1.27069625]
 [0.98404672 1.20948907 0.84305095]
 [1.14006213 1.42810711 1.09771074]]
the d_output is 
 [[ 2.22524649e-03]
 [-2.21018233e-03]
 [-8.37016419e-05]]
[[1.18718853 1.58780447 1.27070692]
 [0.98405031 1.20949186 0.84305685]
 [1.14006674 1.42811069 1.09771832]]
the d_output is 
 [[ 2.22501460e-03]
 [-2.21036388e-03]
 [-8.38978011e-05]]
[[1.18719502 1.5878095  1.2707176 ]
 [0.9840539  1.20949464 0.84306275]
 [1.14007134 1.42811427 1.0977259 ]]
the d_output is 
 [[ 2.22478389e-03]
 [-2.21054444e-03]
 [-8.40929179e-05]]
[[1.18720151 1.58781453 1.27072826]
 [0.98405748 1.20949742 0.84306864]
 [1.14007594 1.42811784 1.09773347]]
the d_output is 
 [[ 2.22455438e-03]
 [-2.21072404e-03]
 [-8.42869979e-05]]
[[1.18720799 1.58781955 1.27073891]
 [0.98406107 1.20950019 0.84307453]
 [1.14008054 1.42812141 1.09774104]]
the d_output is 
 [[ 2.22432605e-03]
 [-2.21090267e-03]
 [-8.44800469e-05]]
[[1.18721448 1.58782457 1.2